package uk.co.gmillns.pad13photobooth;
import android.Manifest; import android.content.*; import android.content.pm.PackageManager; import android.net.Uri; import android.os.*; import android.provider.MediaStore; import android.view.*; import android.widget.*;
import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.annotation.NonNull; import androidx.appcompat.app.AppCompatActivity; import androidx.camera.core.*; import androidx.camera.lifecycle.ProcessCameraProvider; import androidx.camera.view.PreviewView; import androidx.core.content.ContextCompat;
import com.google.common.util.concurrent.ListenableFuture; import java.io.*; import java.text.SimpleDateFormat; import java.util.*;
public class MainActivity extends AppCompatActivity {
 private PreviewView previewView; private ImageView photoPreview; private TextView countdown,message; private LinearLayout cameraControls,reviewControls; private View flash; private ImageCapture imageCapture; private File pendingPhoto; private final Handler handler=new Handler(Looper.getMainLooper());
 private final ActivityResultLauncher<String> cameraPermission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),g->{if(g)startCamera();else Toast.makeText(this,"Camera permission is required.",Toast.LENGTH_LONG).show();});
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);hideSystemUi(); previewView=findViewById(R.id.previewView);previewView.setScaleType(PreviewView.ScaleType.FILL_CENTER);photoPreview=findViewById(R.id.photoPreview);countdown=findViewById(R.id.countdown);message=findViewById(R.id.message);cameraControls=findViewById(R.id.cameraControls);reviewControls=findViewById(R.id.reviewControls);flash=findViewById(R.id.flash);findViewById(R.id.takePhoto).setOnClickListener(v->beginCountdown());findViewById(R.id.retake).setOnClickListener(v->resetToCamera());findViewById(R.id.keep).setOnClickListener(v->keepPhoto());if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)startCamera();else cameraPermission.launch(Manifest.permission.CAMERA);}
 private void hideSystemUi(){if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}else getWindow().getDecorView().setSystemUiVisibility(5894);}
 private void startCamera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();Preview pr=new Preview.Builder().build();pr.setSurfaceProvider(previewView.getSurfaceProvider());imageCapture=new ImageCapture.Builder().setCaptureMode(ImageCapture.CAPTURE_MODE_MAXIMIZE_QUALITY).build();p.unbindAll();CameraSelector s=p.hasCamera(CameraSelector.DEFAULT_FRONT_CAMERA)?CameraSelector.DEFAULT_FRONT_CAMERA:CameraSelector.DEFAULT_BACK_CAMERA;p.bindToLifecycle(this,s,pr,imageCapture);}catch(Exception e){Toast.makeText(this,"Unable to start camera: "+e.getMessage(),Toast.LENGTH_LONG).show();}},ContextCompat.getMainExecutor(this));}
 private void beginCountdown(){cameraControls.setVisibility(View.GONE);countdown.setVisibility(View.VISIBLE);showCount(3);}
 private void showCount(int n){if(n==0){countdown.setVisibility(View.GONE);flash.setVisibility(View.VISIBLE);flash.setAlpha(1f);flash.animate().alpha(0f).setDuration(220).withEndAction(()->flash.setVisibility(View.GONE)).start();capturePhoto();return;}countdown.setText(String.valueOf(n));countdown.setScaleX(.7f);countdown.setScaleY(.7f);countdown.setAlpha(.3f);countdown.animate().scaleX(1).scaleY(1).alpha(1).setDuration(250).start();handler.postDelayed(()->showCount(n-1),850);}
 private void capturePhoto(){if(imageCapture==null){resetToCamera();return;}pendingPhoto=new File(getCacheDir(),"booth_"+System.currentTimeMillis()+".jpg");ImageCapture.OutputFileOptions o=new ImageCapture.OutputFileOptions.Builder(pendingPhoto).build();imageCapture.takePicture(o,ContextCompat.getMainExecutor(this),new ImageCapture.OnImageSavedCallback(){public void onImageSaved(@NonNull ImageCapture.OutputFileResults r){photoPreview.setImageURI(Uri.fromFile(pendingPhoto));photoPreview.setVisibility(View.VISIBLE);previewView.setVisibility(View.GONE);reviewControls.setVisibility(View.VISIBLE);}public void onError(@NonNull ImageCaptureException e){Toast.makeText(MainActivity.this,"Photo failed: "+e.getMessage(),Toast.LENGTH_LONG).show();resetToCamera();}});}
 private void keepPhoto(){if(pendingPhoto==null||!pendingPhoto.exists())return;try{String stamp=new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.UK).format(new Date());ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"BaringLadies_"+stamp+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/LadiesNightPhotoBooth");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u==null)throw new Exception("Unable to create image");try(FileInputStream in=new FileInputStream(pendingPhoto);OutputStream out=getContentResolver().openOutputStream(u)){if(out==null)throw new Exception("Unable to open image");byte[] buf=new byte[8192];int len;while((len=in.read(buf))>0)out.write(buf,0,len);}pendingPhoto.delete();pendingPhoto=null;reviewControls.setVisibility(View.GONE);photoPreview.setVisibility(View.GONE);message.setText("THANK YOU!\nYour photo has been saved.");message.setVisibility(View.VISIBLE);handler.postDelayed(this::resetToCamera,2500);}catch(Exception e){Toast.makeText(this,"Could not save photo: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void resetToCamera(){if(pendingPhoto!=null&&pendingPhoto.exists())pendingPhoto.delete();pendingPhoto=null;photoPreview.setImageDrawable(null);photoPreview.setVisibility(View.GONE);reviewControls.setVisibility(View.GONE);message.setVisibility(View.GONE);countdown.setVisibility(View.GONE);previewView.setVisibility(View.VISIBLE);cameraControls.setVisibility(View.VISIBLE);hideSystemUi();}
 @Override protected void onResume(){super.onResume();hideSystemUi();}
}